project:
  type: website
  output-dir: docs

website:
  title: "Prasansha Ojha - Data Analyst Portfolio"
  navbar:
    logo: ""
    search: false
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Skills"
        href: skills.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
